apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-app
  # pod template
  template:
    metadata:
      labels:
        run: my-app
    spec:
      containers:
      - name: my-app
        image: hello-world
        imagePullPolicy: Always
