apiVersion: "v1"
kind: "Service"
metadata:
  name: "my-app"
  namespace: "default"
  labels:
    run: "my-app"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    run: "my-app"
  type: "ClusterIP"